/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AuthLoginDto } from '../model/authLoginDto';
import { AuthLoginResponse } from '../model/authLoginResponse';
import { AuthRegisterDto } from '../model/authRegisterDto';
import { ExceptionResponse } from '../model/exceptionResponse';
import { User } from '../model/user';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class AuthService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * 
     * 
     * @param authLoginDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authControllerLoginOpts.config] Override http request option.
     */
    public authControllerLogin(authLoginDto: AuthLoginDto, authControllerLoginOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<AuthLoginResponse>>;
    public authControllerLogin(authLoginDto: AuthLoginDto, authControllerLoginOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (authLoginDto === null || authLoginDto === undefined) {
            throw new Error('Required parameter authLoginDto was null or undefined when calling authControllerLogin.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<AuthLoginResponse>(`${this.basePath}/auth/login`,
                    authLoginDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authControllerLoginOpts?.config,
                        headers: {...headers, ...authControllerLoginOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authControllerMeOpts.config] Override http request option.
     */
    public authControllerMe(authControllerMeOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<object>>>;
    public authControllerMe(authControllerMeOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // authentication (bearer) required
        if (typeof this.configuration.accessToken === 'function') {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken()));
        } else if (this.configuration.accessToken) {
            accessTokenObservable = from(Promise.resolve(this.configuration.accessToken));
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<object>>(`${this.basePath}/auth`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authControllerMeOpts?.config,
                        headers: {...headers, ...authControllerMeOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param authRegisterDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [authControllerRegisterOpts.config] Override http request option.
     */
    public authControllerRegister(authRegisterDto: AuthRegisterDto, authControllerRegisterOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<User>>;
    public authControllerRegister(authRegisterDto: AuthRegisterDto, authControllerRegisterOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (authRegisterDto === null || authRegisterDto === undefined) {
            throw new Error('Required parameter authRegisterDto was null or undefined when calling authControllerRegister.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<User>(`${this.basePath}/auth/register`,
                    authRegisterDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...authControllerRegisterOpts?.config,
                        headers: {...headers, ...authControllerRegisterOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
