/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Contact } from '../model/contact';
import { CreateContactDto } from '../model/createContactDto';
import { HttpExceptionDto } from '../model/httpExceptionDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class ContactsService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * 
     * 
     * @param createContactDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [contactsControllerCreateOpts.config] Override http request option.
     */
    public contactsControllerCreate(createContactDto: CreateContactDto, contactsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Contact>>;
    public contactsControllerCreate(createContactDto: CreateContactDto, contactsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (createContactDto === null || createContactDto === undefined) {
            throw new Error('Required parameter createContactDto was null or undefined when calling contactsControllerCreate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<Contact>(`${this.basePath}/contacts`,
                    createContactDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerCreateOpts?.config,
                        headers: {...headers, ...contactsControllerCreateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [contactsControllerDeleteOpts.config] Override http request option.
     */
    public contactsControllerDelete(id: number, contactsControllerDeleteOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Contact>>;
    public contactsControllerDelete(id: number, contactsControllerDeleteOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contactsControllerDelete.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<Contact>(`${this.basePath}/contacts/remove/${encodeURIComponent(String(id))}/active`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerDeleteOpts?.config,
                        headers: {...headers, ...contactsControllerDeleteOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param pageIndex 
     * @param pageSize 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [contactsControllerFindAllOpts.config] Override http request option.
     */
    public contactsControllerFindAll(pageIndex?: number, pageSize?: number, contactsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Contact>>>;
    public contactsControllerFindAll(pageIndex?: number, pageSize?: number, contactsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let queryParameters = new URLSearchParams();
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters.append('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters.append('pageSize', <any>pageSize);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Contact>>(`${this.basePath}/contacts`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerFindAllOpts?.config,
                        headers: {...headers, ...contactsControllerFindAllOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [contactsControllerFindAllActiveOpts.config] Override http request option.
     */
    public contactsControllerFindAllActive(contactsControllerFindAllActiveOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public contactsControllerFindAllActive(contactsControllerFindAllActiveOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/contacts/active`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerFindAllActiveOpts?.config,
                        headers: {...headers, ...contactsControllerFindAllActiveOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param id 
     * @param createContactDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [contactsControllerUpdateOpts.config] Override http request option.
     */
    public contactsControllerUpdate(id: number, createContactDto: CreateContactDto, contactsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Contact>>;
    public contactsControllerUpdate(id: number, createContactDto: CreateContactDto, contactsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contactsControllerUpdate.');
        }

        if (createContactDto === null || createContactDto === undefined) {
            throw new Error('Required parameter createContactDto was null or undefined when calling contactsControllerUpdate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<Contact>(`${this.basePath}/contacts/${encodeURIComponent(String(id))}`,
                    createContactDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerUpdateOpts?.config,
                        headers: {...headers, ...contactsControllerUpdateOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
