/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AddRoleDto } from '../model/addRoleDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';


@Injectable()
export class UsersAdminService {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * 
     * 
     * @param addRoleDto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersAdminControllerAddRoleOpts.config] Override http request option.
     */
    public usersAdminControllerAddRole(addRoleDto: AddRoleDto, usersAdminControllerAddRoleOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public usersAdminControllerAddRole(addRoleDto: AddRoleDto, usersAdminControllerAddRoleOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (addRoleDto === null || addRoleDto === undefined) {
            throw new Error('Required parameter addRoleDto was null or undefined when calling usersAdminControllerAddRole.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/users-admin/roles`,
                    addRoleDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerAddRoleOpts?.config,
                        headers: {...headers, ...usersAdminControllerAddRoleOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param type 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersAdminControllerErrorOpts.config] Override http request option.
     */
    public usersAdminControllerError(type: string, usersAdminControllerErrorOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public usersAdminControllerError(type: string, usersAdminControllerErrorOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling usersAdminControllerError.');
        }

        let queryParameters = new URLSearchParams();
        if (type !== undefined && type !== null) {
            queryParameters.append('type', <any>type);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<any>(`${this.basePath}/users-admin/error`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerErrorOpts?.config,
                        headers: {...headers, ...usersAdminControllerErrorOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param userId 
     * @param roleName 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param {*} [usersAdminControllerRemoveRoleOpts.config] Override http request option.
     */
    public usersAdminControllerRemoveRole(userId: string, roleName: 'admin' | 'root', usersAdminControllerRemoveRoleOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public usersAdminControllerRemoveRole(userId: string, roleName: 'admin' | 'root', usersAdminControllerRemoveRoleOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        if (userId === null || userId === undefined) {
            throw new Error('Required parameter userId was null or undefined when calling usersAdminControllerRemoveRole.');
        }

        if (roleName === null || roleName === undefined) {
            throw new Error('Required parameter roleName was null or undefined when calling usersAdminControllerRemoveRole.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/users-admin/roles/${encodeURIComponent(String(userId))}/${encodeURIComponent(String(roleName))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerRemoveRoleOpts?.config,
                        headers: {...headers, ...usersAdminControllerRemoveRoleOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
