/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddRoleDto { 
    userId: number;
    roleName: AddRoleDto.RoleNameEnum;
}
export namespace AddRoleDto {
    export type RoleNameEnum = 'admin' | 'root';
    export const RoleNameEnum = {
        Admin: 'admin' as RoleNameEnum,
        Root: 'root' as RoleNameEnum
    };
}


