/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { Contact } from '../model/contact';
import { CreateContactDto } from '../model/createContactDto';
import { CreateContactResponse } from '../model/createContactResponse';
import { ErrorResponse } from '../model/errorResponse';
import { UpdateContactDto } from '../model/updateContactDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for contactsControllerCreate operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerCreateRequest
 */
export interface ContactsApiContactsControllerCreateRequest {
    /**
     * 
     * @type {CreateContactDto}
     * @memberof ContactsApiContactsControllerCreate
     */
    readonly 'CreateContactDto': CreateContactDto
}

/**
 * Request parameters for contactsControllerFindAll operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerFindAllRequest
 */
export interface ContactsApiContactsControllerFindAllRequest {
    /**
     * 
     * @type {number}
     * @memberof ContactsApiContactsControllerFindAll
     */
    readonly pageIndex?: number

    /**
     * 
     * @type {number}
     * @memberof ContactsApiContactsControllerFindAll
     */
    readonly pageSize?: number

    /**
     * 
     * @type {string}
     * @memberof ContactsApiContactsControllerFindAll
     */
    readonly sortBy?: string

    /**
     * 
     * @type {'asc' | 'desc'}
     * @memberof ContactsApiContactsControllerFindAll
     */
    readonly sortDir?: 'asc' | 'desc'
}

/**
 * Request parameters for contactsControllerFindOne operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerFindOneRequest
 */
export interface ContactsApiContactsControllerFindOneRequest {
    /**
     * 
     * @type {number}
     * @memberof ContactsApiContactsControllerFindOne
     */
    readonly id: number
}

/**
 * Request parameters for contactsControllerRemove operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerRemoveRequest
 */
export interface ContactsApiContactsControllerRemoveRequest {
    /**
     * 
     * @type {number}
     * @memberof ContactsApiContactsControllerRemove
     */
    readonly id: number
}

/**
 * Request parameters for contactsControllerUpdate operation in ContactsApi.
 * @export
 * @interface ContactsApiContactsControllerUpdateRequest
 */
export interface ContactsApiContactsControllerUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof ContactsApiContactsControllerUpdate
     */
    readonly id: number

    /**
     * 
     * @type {UpdateContactDto}
     * @memberof ContactsApiContactsControllerUpdate
     */
    readonly 'UpdateContactDto': UpdateContactDto
}


@Injectable()
export class ContactsApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * 
     * 
     * @param {ContactsApiContactsControllerCreateRequest} requestParameters Request parameters.
     * @param {*} [contactsControllerCreateOpts.config] Override http request option.
     */
    public contactsControllerCreate(requestParameters: ContactsApiContactsControllerCreateRequest, contactsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<CreateContactResponse>>;
    public contactsControllerCreate(requestParameters: ContactsApiContactsControllerCreateRequest, contactsControllerCreateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'CreateContactDto': createContactDto,
        } = requestParameters;

        if (createContactDto === null || createContactDto === undefined) {
            throw new Error('Required parameter createContactDto was null or undefined when calling contactsControllerCreate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<CreateContactResponse>(`${this.basePath}/contacts`,
                    createContactDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerCreateOpts?.config,
                        headers: {...headers, ...contactsControllerCreateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {ContactsApiContactsControllerFindAllRequest} requestParameters Request parameters.
     * @param {*} [contactsControllerFindAllOpts.config] Override http request option.
     */
    public contactsControllerFindAll(requestParameters: ContactsApiContactsControllerFindAllRequest, contactsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<Contact>>>;
    public contactsControllerFindAll(requestParameters: ContactsApiContactsControllerFindAllRequest, contactsControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            pageIndex,
            pageSize,
            sortBy,
            sortDir,
        } = requestParameters;

        let queryParameters = new URLSearchParams();
        if (pageIndex !== undefined && pageIndex !== null) {
            queryParameters.append('pageIndex', <any>pageIndex);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters.append('pageSize', <any>pageSize);
        }
        if (sortBy !== undefined && sortBy !== null) {
            queryParameters.append('sortBy', <any>sortBy);
        }
        if (sortDir !== undefined && sortDir !== null) {
            queryParameters.append('sortDir', <any>sortDir);
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<Contact>>(`${this.basePath}/contacts`,
                    {
                        params: queryParameters,
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerFindAllOpts?.config,
                        headers: {...headers, ...contactsControllerFindAllOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {ContactsApiContactsControllerFindOneRequest} requestParameters Request parameters.
     * @param {*} [contactsControllerFindOneOpts.config] Override http request option.
     */
    public contactsControllerFindOne(requestParameters: ContactsApiContactsControllerFindOneRequest, contactsControllerFindOneOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Contact>>;
    public contactsControllerFindOne(requestParameters: ContactsApiContactsControllerFindOneRequest, contactsControllerFindOneOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contactsControllerFindOne.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Contact>(`${this.basePath}/contacts/${encodeURIComponent(String(id))}`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerFindOneOpts?.config,
                        headers: {...headers, ...contactsControllerFindOneOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {ContactsApiContactsControllerRemoveRequest} requestParameters Request parameters.
     * @param {*} [contactsControllerRemoveOpts.config] Override http request option.
     */
    public contactsControllerRemove(requestParameters: ContactsApiContactsControllerRemoveRequest, contactsControllerRemoveOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Contact>>;
    public contactsControllerRemove(requestParameters: ContactsApiContactsControllerRemoveRequest, contactsControllerRemoveOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contactsControllerRemove.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<Contact>(`${this.basePath}/contacts/remove/${encodeURIComponent(String(id))}/active`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerRemoveOpts?.config,
                        headers: {...headers, ...contactsControllerRemoveOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {ContactsApiContactsControllerUpdateRequest} requestParameters Request parameters.
     * @param {*} [contactsControllerUpdateOpts.config] Override http request option.
     */
    public contactsControllerUpdate(requestParameters: ContactsApiContactsControllerUpdateRequest, contactsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Contact>>;
    public contactsControllerUpdate(requestParameters: ContactsApiContactsControllerUpdateRequest, contactsControllerUpdateOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            id,
            'UpdateContactDto': updateContactDto,
        } = requestParameters;

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling contactsControllerUpdate.');
        }

        if (updateContactDto === null || updateContactDto === undefined) {
            throw new Error('Required parameter updateContactDto was null or undefined when calling contactsControllerUpdate.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.patch<Contact>(`${this.basePath}/contacts/${encodeURIComponent(String(id))}`,
                    updateContactDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsControllerUpdateOpts?.config,
                        headers: {...headers, ...contactsControllerUpdateOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {*} [contactsV2ControllerFindAllOpts.config] Override http request option.
     */
    public contactsV2ControllerFindAll(contactsV2ControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<Array<string>>>;
    public contactsV2ControllerFindAll(contactsV2ControllerFindAllOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<Array<string>>(`${this.basePath}/v2/contacts`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...contactsV2ControllerFindAllOpts?.config,
                        headers: {...headers, ...contactsV2ControllerFindAllOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
