/**
 * Mój Projekt w Nest
 * Przykładowy projekt w Node.js i TypeScript
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import { Observable, from, of, switchMap } from 'rxjs';
import { AddRoleDto } from '../model/addRoleDto';
import { Configuration } from '../configuration';
import { COLLECTION_FORMATS } from '../variables';

/**
 * Request parameters for usersAdminControllerAddRole operation in UsersAdminApi.
 * @export
 * @interface UsersAdminApiUsersAdminControllerAddRoleRequest
 */
export interface UsersAdminApiUsersAdminControllerAddRoleRequest {
    /**
     * 
     * @type {AddRoleDto}
     * @memberof UsersAdminApiUsersAdminControllerAddRole
     */
    readonly 'AddRoleDto': AddRoleDto
}

/**
 * Request parameters for usersAdminControllerRemoveRole operation in UsersAdminApi.
 * @export
 * @interface UsersAdminApiUsersAdminControllerRemoveRoleRequest
 */
export interface UsersAdminApiUsersAdminControllerRemoveRoleRequest {
    /**
     * 
     * @type {AddRoleDto}
     * @memberof UsersAdminApiUsersAdminControllerRemoveRole
     */
    readonly 'AddRoleDto': AddRoleDto
}


@Injectable()
export class UsersAdminApi {

    protected basePath = 'http://localhost';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();
    protected httpClient: HttpService;

    constructor(httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
        this.httpClient = configuration?.httpClient || httpClient;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * 
     * 
     * @param {UsersAdminApiUsersAdminControllerAddRoleRequest} requestParameters Request parameters.
     * @param {*} [usersAdminControllerAddRoleOpts.config] Override http request option.
     */
    public usersAdminControllerAddRole(requestParameters: UsersAdminApiUsersAdminControllerAddRoleRequest, usersAdminControllerAddRoleOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public usersAdminControllerAddRole(requestParameters: UsersAdminApiUsersAdminControllerAddRoleRequest, usersAdminControllerAddRoleOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'AddRoleDto': addRoleDto,
        } = requestParameters;

        if (addRoleDto === null || addRoleDto === undefined) {
            throw new Error('Required parameter addRoleDto was null or undefined when calling usersAdminControllerAddRole.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.post<any>(`${this.basePath}/users-admin/user/add-role`,
                    addRoleDto,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerAddRoleOpts?.config,
                        headers: {...headers, ...usersAdminControllerAddRoleOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {UsersAdminApiUsersAdminControllerRemoveRoleRequest} requestParameters Request parameters.
     * @param {*} [usersAdminControllerRemoveRoleOpts.config] Override http request option.
     */
    public usersAdminControllerRemoveRole(requestParameters: UsersAdminApiUsersAdminControllerRemoveRoleRequest, usersAdminControllerRemoveRoleOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<any>>;
    public usersAdminControllerRemoveRole(requestParameters: UsersAdminApiUsersAdminControllerRemoveRoleRequest, usersAdminControllerRemoveRoleOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        const {
            'AddRoleDto': addRoleDto,
        } = requestParameters;

        if (addRoleDto === null || addRoleDto === undefined) {
            throw new Error('Required parameter addRoleDto was null or undefined when calling usersAdminControllerRemoveRole.');
        }

        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.delete<any>(`${this.basePath}/users-admin/user/remove-role`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerRemoveRoleOpts?.config,
                        headers: {...headers, ...usersAdminControllerRemoveRoleOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {*} [usersAdminControllerSearchOpts.config] Override http request option.
     */
    public usersAdminControllerSearch(usersAdminControllerSearchOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<object>>;
    public usersAdminControllerSearch(usersAdminControllerSearchOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<object>(`${this.basePath}/users-admin/search`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerSearchOpts?.config,
                        headers: {...headers, ...usersAdminControllerSearchOpts?.config?.headers},
                    }
                );
            })
        );
    }
    /**
     * 
     * 
     * @param {*} [usersAdminControllerSearchPromiseOpts.config] Override http request option.
     */
    public usersAdminControllerSearchPromise(usersAdminControllerSearchPromiseOpts?: { config?: AxiosRequestConfig }): Observable<AxiosResponse<string>>;
    public usersAdminControllerSearchPromise(usersAdminControllerSearchPromiseOpts?: { config?: AxiosRequestConfig }): Observable<any> {
        let headers = {...this.defaultHeaders};

        let accessTokenObservable: Observable<any> = of(null);

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];
        return accessTokenObservable.pipe(
            switchMap((accessToken) => {
                if (accessToken) {
                    headers['Authorization'] = `Bearer ${accessToken}`;
                }

                return this.httpClient.get<string>(`${this.basePath}/users-admin/search-promise`,
                    {
                        withCredentials: this.configuration.withCredentials,
                        ...usersAdminControllerSearchPromiseOpts?.config,
                        headers: {...headers, ...usersAdminControllerSearchPromiseOpts?.config?.headers},
                    }
                );
            })
        );
    }
}
